development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: NIAHChildcare_staging_development
  pool: 5
  username: niahchildcare
  password: StagingNIAHChildcarePassword
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: NIAHChildcare_staging_test
  pool: 5
  username: niahchildcare
  password: StagingNIAHChildcarePassword
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: NIAHChildcare_staging
  pool: 5
  username: niahchildcare
  password: StagingNIAHChildcarePassword
  host: localhost
