development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: NIAHChildcare_production_development
  pool: 5
  username: niahchildcare
  password: ProductionNIAHChildcarePassword
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: NIAHChildcare_production_test
  pool: 5
  username: niahchildcare
  password: ProductionNIAHChildcarePassword
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: NIAHChildcare_production
  pool: 5
  username: niahchildcare
  password: ProductionNIAHChildcarePassword
  host: localhost
