defaults: &defaults
  # HTTP access mode:
  # 1. closed - Authenticate with HTTP basic
  # 2. open - Don't authenticate with HTTP basic
  http_basic_access_mode: closed
  CLOSED: closed
  OPEN: open

  http_basic_name: preview
  http_basic_password: dev # Update this in production
  test_user_password: password

  application_name: NIAHChildcare
  applications_folder: "/var/Apps"
  gemset_name: niahchildcare-rails.3.2.x
  ruby_version: ruby-2.1.5
  user: deploy


  miniumum_version_of_bundler: ">=1.5.2"
  miniumum_version_of_rake: ">=10.1.0"


  # Multi-stage recipe settings
  # Virtual deployment
  virtual_deployment_path: virtual
  virtual_repository_deployment_branch: master
  virtual_server_name: rails.pcsvm
  virtual_stage_name: virtual

  # Staging deployment
  staging_deployment_path: staging
  staging_repository_deployment_branch: master
  staging_server_name: asher.vps
  staging_stage_name: staging

  # Production deployment
  production_deployment_path: production
  production_repository_deployment_branch: master
  production_server_name: gad.vps
  production_stage_name: production


  # Asset vault
  asset_vault_path: /var/AssetsVault


  # Email settings
  email_address: "smtpout.secureserver.net"
  email_domain: "www.niahchildcare.com"
  email_password: "password" # Update this in production
  #email_port: 465
  email_port: 25

  email_user_name: "notifications@niahchildcare.com"

  # ActionMailer settings
  application_server_name: "niahchildcare.com"

  # Email address to send notifications to
  admin_at_niahchildcare: "admin@niahchildcare.com"
  itsupport_at_pencilcasestudios: "itsupport+niahchildcare@pencilcasestudios.com"

  # Norton Web Safe
  norton_web_safe: "jsu2o63-hgeulspig82e1-tiretqrpub66f1-cg04edbg9uqx9ya4jc3x8l7833g59xkvulx3ncqk85k8etjc1imp75qjf4u43u7q1tg2clynpt3kaod89ox44xdc6vk"

  # Password reset window (in hours)
  password_reset_window: 25

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

  # HTTP access mode:
  # 1. closed - Authenticate with HTTP basic
  # 2. open - Don't authenticate with HTTP basic
  http_basic_access_mode: closed
