defaults: &defaults
  http_basic_name: preview
  http_basic_password: future # Update this in production
  test_user_password: password

  # Multi-stage recipe settings
  application_name: NIAHChildcare
  deployment_path_production: production
  deployment_path_staging: staging
  gemset_name: niahchildcare-rails.3.2.x
  repository_deployment_branch: master
  repository_server_name: niahchildcare.com
  ruby_version: ruby-2.0.0-p0
  server_name_production: niahchildcare.com
  server_name_staging: niahchildcare.clientcase.net
  stage_name_production: production
  stage_name_staging: staging
  user: silumesii

  # Application mode:
  # 1. protected    - Authenticate with HTTP basic
  # 2. unprotected  - Don't authenticate with HTTP basic
  mode: protected

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
